name: leran
description: "A new Flutter project."
publish_to: "none"

version: 2.0.0+6

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  window_manager: ^0.3.7
  #for folder permission
  file_picker: ^10.3.10
  #for remembering permission
  shared_preferences: ^2.5.5

  sqflite: ^2.3.0 # for android/IOS/macOS
  sqflite_common_ffi: ^2.3.0 #for windows/linux
  path: ^1.8.3

  http: ^1.6.0
  qr_flutter: ^4.1.0

  #for providing the isar db path for internal disk
  path_provider: ^2.1.5

  url_launcher: ^6.2.5
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/bin/
