// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRIQ2qZw86izF0UefXGwmPEWDR-llr-ns',
    appId: '1:561731142108:web:25d080c7d4c340909d0f19',
    messagingSenderId: '561731142108',
    projectId: 'flutter-demo-c105e',
    authDomain: 'flutter-demo-c105e.firebaseapp.com',
    storageBucket: 'flutter-demo-c105e.firebasestorage.app',
    measurementId: 'G-N4KLYEL8GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Xg68L1FUhfBIcUSPTkIGEz_J3kKsHtY',
    appId: '1:561731142108:android:f7002568fbe66b2f9d0f19',
    messagingSenderId: '561731142108',
    projectId: 'flutter-demo-c105e',
    storageBucket: 'flutter-demo-c105e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOWGW_5B9LDxtK0PZC9b91i0Ra8AAtOYk',
    appId: '1:561731142108:ios:63c9f7967c494faa9d0f19',
    messagingSenderId: '561731142108',
    projectId: 'flutter-demo-c105e',
    storageBucket: 'flutter-demo-c105e.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOWGW_5B9LDxtK0PZC9b91i0Ra8AAtOYk',
    appId: '1:561731142108:ios:63c9f7967c494faa9d0f19',
    messagingSenderId: '561731142108',
    projectId: 'flutter-demo-c105e',
    storageBucket: 'flutter-demo-c105e.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRIQ2qZw86izF0UefXGwmPEWDR-llr-ns',
    appId: '1:561731142108:web:6823e991499be4269d0f19',
    messagingSenderId: '561731142108',
    projectId: 'flutter-demo-c105e',
    authDomain: 'flutter-demo-c105e.firebaseapp.com',
    storageBucket: 'flutter-demo-c105e.firebasestorage.app',
    measurementId: 'G-CZTQ11QTCM',
  );
}
